### ISSUE TITLE
При ответе на сообщение в чате, приложение падает с ошибкой

### ISSUE THREAD

**Issue by baihu92** [carrotquest/ios-sdk#11]
Здравствуйте. При отправке сообщения в чате, приложение падает с ошибкой. 
Чат открывался по нажатию на пуш-нотификацию.
Версия - 2.0.1

Ошибка:
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x875a8949a020)`

**Comment by Alond** [comment]
@baihu92 Привет, взял в работу.

**Comment by Alond** [comment]
@baihu92 Привет! Не могу повторить :( Есть тестовый проект или более подробное описание как повторить?

**Comment by baihu92** [comment]
Приложение написано на flutter'e. 

При старте вызывается
- Carrot.shared.setup
- CarrotNotificationService.shared.setToken

AppDelegate следующий:

```
import UIKit
import Flutter
import Firebase
import CarrotSDK

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate, MessagingDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
    ) -> Bool {
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
        }
        
        GeneratedPluginRegistrant.register(with: self)
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    override func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification,
        withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let notificationService = CarrotNotificationService.shared
        if notificationService.canHandle(notification) {
            notificationService.show(notification, completionHandler: completionHandler)
        }
    }
    
    override func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        didReceive response: UNNotificationResponse,
        withCompletionHandler completionHandler: @escaping () -> Void) {
        let notificationService = CarrotNotificationService.shared
        if notificationService.canHandle(response) {
            notificationService.clickNotification(notificationResponse: response)
        }
        
        completionHandler()
    }
}
```

Тестировал на устройстве (не симулятор).

Ситуация при которой происходит креш:
- приложение было открыто и на переднем плане (с закрытого приложения и из фона не тестировал);
- приходит нотификация (сообщение из чата);
- при открытии нотификации, открывается чат;
- пишется ответ в чате и нажимается кнопка отправки;

Далее приложение падает с указанной ошибкой.

**Comment by Alond** [comment]
@baihu92 Не смог повторить на свифте. Тестового проекта нет?

**Comment by Dimoshka** [comment]
@Alond 
Возможно ответ находится тут
https://stackoverflow.com/a/63869774

Up - проблема таже, только я не пытаюсь исползовать фаирбейс.

**Comment by Dimoshka** [comment]
Вроде бы работает, можно закрывать
