### ISSUE TITLE
Messages infinity loading

### ISSUE THREAD

**Issue by MrOlolo** [carrotquest/ios-sdk#12]
I get infinity loading when send messages(_pic. 1_)

But at admin panel i got this messages and already answered(_pic. 2_)

To fix this i can open history and return back or reopen chat

Device: Simulator iPhone SE iOS 11.4

![image](https://user-images.githubusercontent.com/24739054/109360198-d68ea700-7897-11eb-9d0b-f3fb686e4c0c.png)
_**pic. 1**_

![image](https://user-images.githubusercontent.com/24739054/109360312-06d64580-7898-11eb-92b6-14ba34fb0107.png)
_**pic. 2**_

![image](https://user-images.githubusercontent.com/24739054/109360470-59affd00-7898-11eb-990a-7211742d9b78.png)
_**pic. 3**_

**Comment by Alond** [comment]
@MrOlolo, уже в работе

**Comment by MrOlolo** [comment]
Seems to be fixed. Cannot Reproduce at version 2.1.1
