### ISSUE TITLE
iOS 14.4. AppCrash when send message

### ISSUE THREAD

**Issue by MrOlolo** [carrotquest/ios-sdk#13]
When i send message at chat app crash with error `Thread 1: EXC_BAD_ACCESS (code=1, address=0x9c22932471f0)`

Everything works fine at simulator with iOS 11.4. 
But at iOS 14.4 app crash. Checked at ipad 2017 and Simulator iPhone 12

**Comment by Alond** [comment]
в работе

**Comment by MrOlolo** [comment]
@Alond Привет! Есть ориентировочные сроки решения проблем?

**Comment by Dimoshka** [comment]
Дубликат #11

**Comment by Dimoshka** [comment]
Теперь в последней версии работает!

**Comment by MrOlolo** [comment]
Error fixed at version 2.1.1
