### ISSUE TITLE
Auth Error with userId

### ISSUE THREAD

**Issue by MrOlolo** [carrotquest/ios-sdk#14]
When i use `Carrot.shared.auth(withUserId: userId, withUserAuthKey: userAuthKey,)` 
I get error `Wrong user serializator`, nevertheless _userId_ updates at admin console.
_UserId_ is UUID format. If i use simple _userId_ like `"1234"` code work without error

**Comment by Alond** [comment]
@MrOlolo, метод Carrot.shared.auth вы вызываете при запуске приложения?

**Comment by MrOlolo** [comment]
> @MrOlolo, метод Carrot.shared.auth вы вызываете при запуске приложения?

Если юзер авторизован, то при запуске приложения. Если нет, то после авторизации

**Comment by Alond** [comment]
@MrOlolo,  достаточно делать только при авторизации. Ошибку я поправлю, сделаю информационное сообщение.

**Comment by mlshvdv** [comment]
@Alond добрый день! Возможно ли оперативно поправить этот баг? Мы интегрируемся с Carrot Quest и очень ждем исправления багов, которые стопят принятие решения в пользу CQ в качестве партнера.

**Comment by MrOlolo** [comment]
При самой первой авторизации (после установки приложения) вылезает такая же ошибка.
Последняя версия SDK.
Тестирую на Simulator iPhone 13(iOS15.0)
