### ISSUE TITLE
Auth error after logout

### ISSUE THREAD

**Issue by alexeybolv** [carrotquest/ios-sdk#15]
Добрый день. 
Делаю в начале logout, а затем авторизую нового пользователя. В это случае всегда выдает ошибку:

<img width="692" alt="Снимок экрана 2021-03-17 в 12 14 43" src="https://user-images.githubusercontent.com/14241858/111443703-b0cc2380-871a-11eb-8f42-1b00964bd736.png">

<img width="462" alt="Снимок экрана 2021-03-17 в 12 15 27" src="https://user-images.githubusercontent.com/14241858/111443725-b590d780-871a-11eb-8eaa-b28c7c6c89d9.png">

версия 2.0.1 
Xcode 12.4

**Comment by alexeybolv** [comment]
Update: 

Если авторизацию обернуть в 
`DispatchQueue.main.asyncAfter(deadline: .now() + 5)`
тогда будет работать.

**Comment by Alond** [comment]
@alexeybolv Привет! Кажется для logout тоже нужно добавить функцию обратного вызова, добавлю к релизу который готовлю

**Comment by mlshvdv** [comment]
@Alond добрый день! Возможно ли оперативно добавить функцию обратного вызова? Очень необходима нам, чтобы завершить интеграцию с Carrot Quest.

**Comment by mlshvdv** [comment]
@Alond ?

**Comment by MrOlolo** [comment]
Up

**Comment by mlshvdv** [comment]
@Alond ?

**Comment by Alond** [comment]
Добавлено
