### ISSUE TITLE
error: module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler:

### ISSUE THREAD

**Issue by Dimoshka** [carrotquest/ios-sdk#18]
Пожалуйста обновите библиотеку!

error: module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler:

**Comment by Dimoshka** [comment]
@Alond

**Comment by MrOlolo** [comment]
Up

**Comment by x2web** [comment]
module compiled with Swift 5.4 cannot be imported by the Swift 5.3.1 compiler: .../Pods/CarrotquestSDK/CarrotSDK.framework/Modules/CarrotSDK.swiftmodule/armv7-apple-ios.swiftmodule

**Comment by sena1or** [comment]
up, please use Build Libraries for Distribution option and/or Xcode 12.5.1 🙏

**Comment by sena1or** [comment]
+ Dashly

**Comment by kaldai** [comment]
UP

**Comment by sena1or** [comment]
Hi folks, how the things going on?
@Alond 🙏

**Comment by Datastore24Kirill** [comment]
UP!
