### ISSUE TITLE
Can't reach successHandler with Carrot.shared.auth

### ISSUE THREAD

**Issue by igibadullin** [carrotquest/ios-sdk#2]
I use sample code, but can't reach successHandler. If I pass wrong id or key - errorHandler is working perfectly.

XCode version 11.5

```
Carrot.shared.auth(
    withUserId: userId, 
    withUserAuthKey: userAuthKey,
        successHandler: {
             print("Carrotquest SDK user auth successed")
        },
        errorHandler: { error in
            print("Carrotquest SDK user auth error: " + error)
        })
```

**Comment by manzick** [comment]
The bug is fixed and submitted for testing. Expect a release soon.

**Comment by Alond** [comment]
@igibadullin 
Hi, can you check it?
```
  pod 'CarrotquestSDK', '1.0.34-beta1'
  pod 'CarrotquestLib', '1.0.23-beta1'
```

**Comment by igibadullin** [comment]
@Alond 
Hello. Auth now works just fine, but when I call Carrot.shared.openChat() application crashes with errors:

dyld: lazy symbol binding failed: Symbol not found
Referenced from: .../Frameworks/CarrotSDK.framework/CarrotSDK
Expected in: .../Frameworks/RxFlow.framework/RxFlow

dyld: Symbol not found
Referenced from: .../Frameworks/CarrotSDK.framework/CarrotSDK
Expected in: .../Frameworks/RxFlow.framework/RxFlow

**Comment by Alond** [comment]
@igibadullin 
Ok, I can't reproduce it. Can you share your project or make new one to reproduce it?

**Comment by igibadullin** [comment]
@Alond 
https://drive.google.com/file/d/1Suidtxze2pMGMNNCnL6gZTTDZ_txSOgA/view?usp=sharing

**Comment by Alond** [comment]
@igibadullin 
build and run success.
1. Download your proj
2. run 
```
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod update
```
3. try to build but failed (strange Firebase error)
4. remove import Firebase from Configurator.swift
5. build -> clean
6. Profit. Run success
