### ISSUE TITLE
Есть ли критичные изменения при обновлении в версии CarrotquestSDK 2.1.9 -> 2.2.0 ?

### ISSUE THREAD

**Issue by x2web** [carrotquest/ios-sdk#20]
# Вопрос

Есть ли критичные изменения при обновлении в версии CarrotquestSDK 2.1.9 -> 2.2.0 ?

# Проблема 

Невозможность использования CarrotquestSDK версии 2.2.0 требующей Swift 5.5.2  
из-за бага на стороне Apple https://developer.apple.com/forums/thread/697184 
Xcode 13.2 не позволяет использовать приложение на iOS ниже версии 13

P.S. Обновите документацию, так как для актуальной версии требуется Swift 5.5.2

**Comment by Alond** [comment]
@x2web обновилась работа с пушами, если не пользуетесь статистикой по доставленным пушам, то не это обновление не актуально
