### ISSUE TITLE
Unsupported Swift architecture

### ISSUE THREAD

**Issue by goodmadima** [carrotquest/ios-sdk#22]
Здравствуйте. Помогите пожалуйста с проблемой.
Не получается импортировать ваш sdk для react-native проекта (Xcode 14)
При попытке импортировать sdk

#import "CarrotSDK/CarrotSDK-Swift.h"

Получаем ошибку

Unsupported Swift architecture

**Comment by Alond** [comment]
Привет! К сожалению, мы не занимаемся поддержкой сдк для react-native.

**Comment by Alond** [comment]
@goodmadima Возможно будет полезно, у нас в настройках проекта arm64 архитектура исключена для симуляторов. Больше никаких специфичных настроек нет.

**Comment by goodmadima** [comment]
В данном случае это никак не отличается от нативной разработки. Приложение не билдится ни на макбуках с процессором intel ни с m1. Устанавливали через pod. Может быть мы можем скинуть какие-то логи, чтобы вы смогли нам как-то попробовать помочь?

**Comment by Alond** [comment]
> Приложение не билдится ни на макбуках с процессором intel ни с m1

Где же оно тогда билдится? Опять же в настройках проекта есть дефолтные для iOS архитектуры их и стараемся поддерживать.

**Comment by goodmadima** [comment]
Здравствуйте. Можете, пожалуйста, прислать пример тестового приложения с использованием вашего sdk? Возможно мы что-то упустили

**Comment by goodmadima** [comment]
@Alond Привет. Вот создал простое приложение https://github.com/goodmadima/Appp, где импортирую ваш sdk и при билде падает с ошибкой

**Comment by Alond** [comment]
@goodmadima Привет. Пустой проект? Не нашел никаких зависимостей

**Comment by goodmadima** [comment]
@Alond прошу прощения, забыл добавить. Обновил

**Comment by Alond** [comment]
@goodmadima Запустил на реальном устройстве, немного [инфо](https://stackoverflow.com/questions/73985070/xcode-14-xcode-archive-error-unsupported-swift-architecture-import-swiftmodule)

**Comment by goodmadima** [comment]
@Alond Да, сбилдилось на реальном устройстве. Спасибо. 
Подскажите еще момент с использованием sdk. Как правильно импортировать ваш sdk?
Я через podfile добавил ваш sdk. 
В файле AppDelegate.m добавил #import <CarrotSDK/CarrotSDK-Swift.h>
Но в методе - (BOOL)application:(UIApplication *)application я не могу вызвать Carrot.shared.setup(... Ругается что нет Carrot

**Comment by Alond** [comment]
@goodmadima к сожалению не силен с ObjC

**Comment by JerakRus** [comment]
@Alond Здравствуйте! А кто силен в ObjC ? А то на главной странице вашего сайта мы указаны как партнеры, а помочь нам интегрировать Ваш SDK в наше приложение некому. 

По итогам что идет не так:
1) Мы используем для разработки кроссплатформеный фраемворк React-Native, но пытаемся подключить ваш фраемворк нативно. Т.е. в данном контексте никаких отличий от нативной разработки на ObjectiveC.
2) У нас получилось собрать приложение импортируя Ваш сдк на реальном устройстве.
При импорте в AppDelegate.m файле
```
#import <CarrotSDK/CarrotSDK-Swift.h>

```
или
```
#import <CarrotSDK/CarrotSDK.h>
```
Xcode собирает приложение и устанавливает на устройство.
3. Если попытаться вывести что-то в консоль
```
NSLog(@"CarrotSDK", Carrot);
```
Или  UserProperty класс, или CarrotSDK - все падает и выдает одну и ту же ошибку (в зависимости от идентификатора):
<img width="308" alt="Снимок экрана 2022-11-15 в 11 17 44" src="https://user-images.githubusercontent.com/35634599/201866162-f9cd6628-d820-4c87-b6ef-26ecbe67feff.png">


Каким идентификатором нужно пользоваться что бы запустить метод или хотя бы просто что-то отобразить?
Поддерживает ли Ваш SDK работу в ObjectiveC?
Если нет, будет ли поддержка?

**Comment by JerakRus** [comment]
Если это можно заставить работать, было бы здорово иметь пример простого приложения с применением вашего. SDK, как то что отправили мы Вам, или как у Вас есть на Андройд

**Comment by Alond** [comment]
@JerakRus Привет! У нас в ближайших планах нет добавления поддержки ObjectiveC. Но я посмотрел документацию, кажется, что ничего сложного в этом нет. Сегодня-завтра сделаю сборку, но тестировать её придется на вас.

**Comment by JerakRus** [comment]
Хорошо, мы поддержим) Спасибо!

**Comment by Alond** [comment]
@JerakRus Сборка не удалась :( Как будут новости сообщу

**Comment by JerakRus** [comment]
@Alond Жаль, тогда ждем

**Comment by piroznoe** [comment]
Есть ли возможность запустить проект с вашим SDK на симуляторе? или если добавить ваш SDK в проект то возможность тестирования на симуляторе пропадёт? 

Например iOS приложение не собирается на Mac с m1 на iPhone Simulator 
если запустить Xcode через rosetta всё будет ок, но тогда очень сильно страдает производительность

**Comment by Alond** [comment]
@piroznoe Привет, сейчас на симуляторе с М процессорами не запускается. Задача запланирована, где-то в конце декабря будет релиз с поддержкой М процессоров.

**Comment by JerakRus** [comment]
@Alond привет, в нашем случае необходимость внедрения вашего SDK в иос сегодня отпала, так что если вдруг кроме нас никому поддержка objective-C не нужна, то можете откладывать в долгий ящик)

**Comment by Alond** [comment]
2.8.0
