### ISSUE TITLE
Unsupported Swift architecture

### ISSUE THREAD

**Issue by rastaman111** [carrotquest/ios-sdk#23]
Всем привет

Обновил либо до версии 2.7.3

И при запуске получаю такие ошибки

Xcode версия 14.1

Как можно решить данную проблему?

<img width="282" alt="Снимок экрана 2022-11-21 в 11 43 03" src="https://user-images.githubusercontent.com/15727518/203004815-a33d895c-5ae7-4794-b75e-d5abb6291a30.png">

**Comment by Alond** [comment]
#22
