### ISSUE TITLE
Undefined symbols for architecture armv7 when i try to archive and distribute adhoc or appstore the application

### ISSUE THREAD

**Issue by Sofrano** [carrotquest/ios-sdk#4]
Hello! 
I get the following logs:

Undefined symbols for architecture armv7:
      "_$s6RxFlow5FlowsCMa", referenced from:
          _$s9CarrotSDK6SdkAppC17createFlowAndOpenyyF in 064.o
      "_$s6RxFlow5FlowsC9whenReady5flow15blockyAA0B0_p_yxctSo16UIViewControllerCRbzlFZ", referenced from:
          _$s9CarrotSDK6SdkAppC17createFlowAndOpenyyF in 064.o
    ld: symbol(s) not found for architecture armv7
    Exited with 1

**Comment by Alond** [comment]
Hi! 
Devices with armv7 architecture are not supported (iOS 9.x.x)

**Comment by Sofrano** [comment]
@Alond Привет!
Не могу решить проблему и с отключенным armv7
Сделал пустой проект, подключил SDK - билдю, запускаю - все работает. Но стоит мне сделать архив и отправить в itunesconnect или adhoc, как проблема просыпается.
С убранным armv7 логи теперь такие:

    -= Output =-
    ld: warning: -sdk_version and -platform_version are not compatible, ignoring -sdk_version
    Undefined symbols for architecture arm64:
      "_$s6RxFlow5FlowsCMa", referenced from:
          _$s9CarrotSDK6SdkAppC17createFlowAndOpenyyF in 064.o
      "_$s6RxFlow5FlowsC9whenReady5flow15blockyAA0B0_p_yxctSo16UIViewControllerCRbzlFZ", referenced from:
          _$s9CarrotSDK6SdkAppC17createFlowAndOpenyyF in 064.o
    ld: symbol(s) not found for architecture arm64
    Exited with 1

![Screenshot 2020-07-10 at 19 17 02](https://user-images.githubusercontent.com/12710696/87158690-f14ce500-c2e1-11ea-9f4d-e6eb27159293.png)

Если убрать ARM64, то начинаются проблемы с pod'ами. 
frameworks.sh: line 144: ARCHS[@]: unbound variable
Где решением будет включение arm64

Не первый день вопрос пытаюсь решить, подскажите что делать.

**Comment by Alond** [comment]
@Sofrano Привет! Займусь этой задачей сегодня-завтра.

**Comment by Sofrano** [comment]
Супер, спасибо!

пн, 13 июля 2020 г. в 11:12, Alond <notifications@github.com>:

**Comment by Sofrano** [comment]
> @Sofrano Привет! Займусь этой задачей сегодня-завтра.

Привет! Как успехи в этом направлении?

**Comment by Alond** [comment]
@Sofrano Привет!
Сделал тестовые сборки, у меня устой проект теперь собирается. Можешь проверить?
```
  pod 'CarrotquestSDK', '1.0.34-beta1'
  pod 'CarrotquestLib', '1.0.23-beta1'
```

**Comment by Sofrano** [comment]
> @Sofrano Привет!
> Сделал тестовые сборки, у меня устой проект теперь собирается. Можешь проверить?
> 
> ```
>   pod 'CarrotquestSDK', '1.0.34-beta1'
>   pod 'CarrotquestLib', '1.0.23-beta1'
> ```

Теперь все отлично! Спасибо!

**Comment by Alond** [comment]
@Sofrano обновил основную сборку
