### ISSUE TITLE
Проблема при отправке сообщений 

### ISSUE THREAD

**Issue by KingSerz** [carrotquest/ios-sdk#5]
Проблема при отправке сообщений в iOS.  Ошибка возникает в RxSwift/Map.swift
Подробности можно посмотреть  по ссылке
[https://on-line.org/FITSTARS/SDK_carrotquest_bug.pdf](url)

**Comment by Alond** [comment]
@KingSerz 
Привет! Есть тестовый проект где это повторяется? Ну или доступ к этому?

**Comment by KingSerz** [comment]
@Alond Я отправил приглашение в проект FitStars, где лежит код.

**Comment by KingSerz** [comment]
@Alond Для авторизации в приложении проще всего нажать e-mail и можно вбить любой вымышленный адрес

**Comment by manzick** [comment]
Привет! Можете пожалуйста добавить меня в тестовый проект?

**Comment by KingSerz** [comment]
> Привет! Можете пожалуйста добавить меня в тестовый проект?

@manzick Привет! Отправил приглашение.

**Comment by Alond** [comment]
@KingSerz Привет! Я пропарил приглашение, повторишь?

**Comment by KingSerz** [comment]
@Alond Привет! Отправил, отпишись плиз пришло или нет.

**Comment by Alond** [comment]
@KingSerz все ок

**Comment by KingSerz** [comment]
> @KingSerz все ок

отлично!
