### ISSUE TITLE
Перестало запускаться приложение под XCode 12

### ISSUE THREAD

**Issue by semen-sequenia** [carrotquest/ios-sdk#6]
После обновления Xcode на версию 12 перестало запускатся приложение. Выводится ошибка компиляции
 Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

**Comment by Sofrano** [comment]
+1

**Comment by voragomod** [comment]
+1

**Comment by x2web** [comment]
+1

**Comment by voragomod** [comment]
@Alond Подскажете, когда проблему закроете?

**Comment by x2web** [comment]
@Alond Какие сроки решения ?

**Comment by Alond** [comment]
@voragomod @x2web Затянулось решение проблемы, но все же мы сделали. Вот версия для тестирования сборки `pod 'CarrotquestSDK', '2.0.0-beta41'`
