### ISSUE TITLE
Проблем апри отправке сообщения 

### ISSUE THREAD

**Issue by KingSerz** [carrotquest/ios-sdk#8]
Проблема при отправке сообщений в iOS. Ошибка возникает в RxSwift/Map.swift
Подробности можно посмотреть по ссылке
https://on-line.org/FITSTARS/SDK_carrotquest_bug.pdf

**Comment by Alond** [comment]
@KingSerz Привет! Завтра выложу сборку с исправленной ошибкой для XCode < 12

**Comment by Alond** [comment]
@KingSerz чутка задерживаюсь со сборкой, надеюсь сегодня

**Comment by x2web** [comment]
@Alond А когда ждать сборку для Xcode 12 ?

**Comment by Alond** [comment]
@x2web там проблемы с cocoapods  и xcode12, вместе со стабильной для xcode 11.x выложу "кривую" версию для разработки с поддержкой xcode12.

**Comment by aShaforostov** [comment]
@Alond Выложили ли версии с фиксом? Как установить?
